name: Semgrep Code Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 3 * * 0'

jobs:
  semgrep:
    name: Semgrep Scan
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Semgrep
        uses: returntocorp/semgrep-action@v1
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
        with:
          config: >-
            p/default
            p/react
            p/typescript
            p/typescript-security
            p/jwt
          generateSarif: true
          outputFile: results.sarif

      - name: List files
        run: ls -la

      - name: Upload SARIF file
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
          wait-for-processing: true
          category: semgrep-results
