name: Semgrep Code Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 3 * * 0'  # Every Sunday at 3 AM UTC

jobs:
  semgrep:
    name: Semgrep Scan
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          publishToken: ${{ secrets.SEMGREP_APP_TOKEN }}
          config: >-
            p/default
            p/react
            p/typescript
            p/typescript-security
            p/jwt
          generateSarif: true
          outputFile: semgrep.sarif

      - name: Upload SARIF file
        if: always()  # Run this step even if Semgrep finds issues
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif
          wait-for-processing: true  # Wait for SARIF to be processed
